# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlastRadius < Formula
  desc "Analyze the blast radius of compromised open-source packages"
  homepage "https://github.com/DataDog/package-blast-radius"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/package-blast-radius/releases/download/v0.0.2/blast-radius_Darwin_x86_64.tar.gz"
      sha256 "e0c87a926a0445731ce501d5c04abbea713614969124eb46ab052a28ba425212"

      define_method(:install) do
        bin.install "blast-radius"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DataDog/package-blast-radius/releases/download/v0.0.2/blast-radius_Darwin_arm64.tar.gz"
      sha256 "643907212e395104559a3fd15d47eac0c1b34a53826f4f46bf9b6e6d1a6b5ad1"

      define_method(:install) do
        bin.install "blast-radius"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/package-blast-radius/releases/download/v0.0.2/blast-radius_Linux_x86_64.tar.gz"
      sha256 "be144f6ac367e69fcef380adf6b341942331d839d4b08c74714dad9ab60b58d5"
      define_method(:install) do
        bin.install "blast-radius"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/package-blast-radius/releases/download/v0.0.2/blast-radius_Linux_arm64.tar.gz"
      sha256 "43f895a7eb6fcd1c688b86a55243528bf049bb3228b5b1e37af183cce1f9eb94"
      define_method(:install) do
        bin.install "blast-radius"
      end
    end
  end
end
