package blast

import (
	"bytes"
	"encoding/csv"
	"encoding/json"
	"reflect"
	"strings"
	"testing"
	"time"
)

func sampleResult() *BlastResult {
	axios := PackageVersion{System: NPM, Name: "axios", Version: "1.14.1"}
	return &BlastResult{
		Targets:    []PackageVersion{axios},
		TotalEdges: 2915977,
		Affected: []AffectedPackage{
			{
				PackageVersion:  PackageVersion{System: NPM, Name: "tremendous", Version: "3.11.0"},
				Depth:           1,
				Path:            []PathStep{{Package: "tremendous", Version: "3.11.0", Requirement: "^1.6.1"}},
				Target:          axios,
				WeeklyDownloads: 24400,
			},
			{
				PackageVersion: PackageVersion{System: NPM, Name: "deep-dep", Version: "2.0.0"},
				Depth:          2,
				Path: []PathStep{
					{Package: "deep-dep", Version: "2.0.0", Requirement: "^3.11.0"},
					{Package: "tremendous", Version: "3.11.0", Requirement: "^1.6.1"},
				},
				Target:          axios,
				WeeklyDownloads: -1,
			},
		},
		UniquePackages: 2,
		MaxDepth:       2,
		Elapsed:        1500 * time.Millisecond,
	}
}

// The JSON shape is a contract: the viewer decodes these exact fields, and
// reports generated by older builds must keep loading.
func TestRenderJSONContract(t *testing.T) {
	var buf bytes.Buffer
	if err := RenderResults(sampleResult(), "json", 0, &buf); err != nil {
		t.Fatalf("RenderResults: %v", err)
	}

	const want = `{
  "target": "axios@1.14.1",
  "targets": [
    {
      "name": "axios",
      "version": "1.14.1"
    }
  ],
  "system": "NPM",
  "total_edges": 2915977,
  "total_affected": 2,
  "unique_packages": 2,
  "max_depth": 2,
  "elapsed": "1.5s",
  "affected": [
    {
      "name": "tremendous",
      "version": "3.11.0",
      "depth": 1,
      "weekly_downloads": 24400,
      "target": "axios@1.14.1",
      "path": [
        {
          "package": "tremendous",
          "version": "3.11.0",
          "requirement": "^1.6.1"
        }
      ]
    },
    {
      "name": "deep-dep",
      "version": "2.0.0",
      "depth": 2,
      "weekly_downloads": -1,
      "target": "axios@1.14.1",
      "path": [
        {
          "package": "deep-dep",
          "version": "2.0.0",
          "requirement": "^3.11.0"
        },
        {
          "package": "tremendous",
          "version": "3.11.0",
          "requirement": "^1.6.1"
        }
      ]
    }
  ]
}
`

	if got := buf.String(); got != want {
		t.Errorf("JSON output changed.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// JSONResult must round-trip through itself, so a report can be read back with
// the same types that wrote it.
func TestRenderJSONRoundTrips(t *testing.T) {
	var buf bytes.Buffer
	if err := RenderResults(sampleResult(), "json", 0, &buf); err != nil {
		t.Fatalf("RenderResults: %v", err)
	}

	var decoded JSONResult
	if err := json.Unmarshal(buf.Bytes(), &decoded); err != nil {
		t.Fatalf("decoding our own output: %v", err)
	}

	if decoded.System != "NPM" || decoded.TotalEdges != 2915977 || decoded.MaxDepth != 2 {
		t.Errorf("metadata lost: %+v", decoded)
	}
	if len(decoded.Affected) != 2 {
		t.Fatalf("got %d affected, want 2", len(decoded.Affected))
	}
	first := decoded.Affected[0]
	if first.Name != "tremendous" || first.WeeklyDownloads != 24400 || first.Target != "axios@1.14.1" {
		t.Errorf("affected[0] = %+v", first)
	}
	if len(decoded.Affected[1].Path) != 2 {
		t.Errorf("affected[1] path = %+v, want 2 hops", decoded.Affected[1].Path)
	}
}

func TestRenderCSV(t *testing.T) {
	var buf bytes.Buffer
	if err := RenderResults(sampleResult(), "csv", 0, &buf); err != nil {
		t.Fatalf("RenderResults: %v", err)
	}

	lines := strings.Split(strings.TrimRight(buf.String(), "\n"), "\n")
	if len(lines) != 3 {
		t.Fatalf("got %d lines, want header + 2 rows:\n%s", len(lines), buf.String())
	}
	if lines[0] != "package,version,depth,weekly_downloads,target,path" {
		t.Errorf("header = %q", lines[0])
	}
	if !strings.HasPrefix(lines[1], "tremendous,3.11.0,1,24400,axios@1.14.1,") {
		t.Errorf("row 1 = %q", lines[1])
	}
	// An unenriched package (-1) must render as an empty cell, not "-1".
	if !strings.HasPrefix(lines[2], "deep-dep,2.0.0,2,,axios@1.14.1,") {
		t.Errorf("row 2 = %q, want an empty downloads cell", lines[2])
	}
}

// deduplicateByName keeps the first row per name, relying on RenderResults
// having sorted by downloads first.
func TestDeduplicateByName(t *testing.T) {
	affected := []AffectedPackage{
		{PackageVersion: PackageVersion{Name: "a", Version: "2.0.0"}, WeeklyDownloads: 500},
		{PackageVersion: PackageVersion{Name: "a", Version: "1.0.0"}, WeeklyDownloads: 100},
		{PackageVersion: PackageVersion{Name: "b", Version: "1.0.0"}, WeeklyDownloads: 300},
	}

	got := deduplicateByName(affected)

	if len(got) != 2 {
		t.Fatalf("got %d rows, want 2", len(got))
	}
	if got[0].Name != "a" || got[0].Version != "2.0.0" {
		t.Errorf("got[0] = %s@%s, want a@2.0.0 (first occurrence wins)", got[0].Name, got[0].Version)
	}
	if got[1].Name != "b" {
		t.Errorf("got[1] = %s, want b", got[1].Name)
	}
}

func TestFormatNumber(t *testing.T) {
	tests := map[int64]string{
		0:          "0",
		7:          "7",
		999:        "999",
		1000:       "1,000",
		24400:      "24,400",
		1271328:    "1,271,328",
		1000000000: "1,000,000,000",
	}
	for in, want := range tests {
		if got := formatNumber(in); got != want {
			t.Errorf("formatNumber(%d) = %q, want %q", in, got, want)
		}
	}
}

func TestTargetsLabel(t *testing.T) {
	pv := func(n, v string) PackageVersion { return PackageVersion{System: NPM, Name: n, Version: v} }

	tests := []struct {
		name    string
		targets []PackageVersion
		want    string
	}{
		{"none", nil, "(none)"},
		{"one", []PackageVersion{pv("axios", "1.14.1")}, "axios@1.14.1"},
		{"three are listed", []PackageVersion{pv("a", "1"), pv("b", "2"), pv("c", "3")}, "a@1, b@2, c@3"},
		{
			"four are summarized",
			[]PackageVersion{pv("a", "1"), pv("a", "2"), pv("b", "1"), pv("c", "1")},
			"4 versions across 3 packages",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := targetsLabel(tt.targets); got != tt.want {
				t.Errorf("targetsLabel() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestFormatPath(t *testing.T) {
	target := PackageVersion{System: NPM, Name: "axios", Version: "1.14.1"}

	if got := formatPath(nil, target); got != "axios@1.14.1" {
		t.Errorf("empty path = %q, want the bare target", got)
	}

	path := []PathStep{
		{Package: "deep-dep", Version: "2.0.0", Requirement: "^3.11.0"},
		{Package: "tremendous", Version: "3.11.0", Requirement: "^1.6.1"},
	}
	want := "deep-dep@2.0.0 ──(^3.11.0)──▶ tremendous@3.11.0 ──(^1.6.1)──▶ axios@1.14.1"
	if got := formatPath(path, target); got != want {
		t.Errorf("formatPath() = %q, want %q", got, want)
	}
}

// Table output is sorted by downloads, so the most impactful package leads.
func TestRenderTableSortsByImpact(t *testing.T) {
	var buf bytes.Buffer
	if err := RenderResults(sampleResult(), "table", 0, &buf); err != nil {
		t.Fatalf("RenderResults: %v", err)
	}

	out := buf.String()
	if !strings.Contains(out, "2,915,977") {
		t.Errorf("edge count not formatted with separators:\n%s", out)
	}
	if strings.Index(out, "tremendous") > strings.Index(out, "deep-dep") {
		t.Errorf("expected the 24,400-download package to sort above the unenriched one:\n%s", out)
	}
}

func TestRenderAffectedPackagesCSV(t *testing.T) {
	result := &BlastResult{
		Affected: []AffectedPackage{
			{PackageVersion: PackageVersion{Name: "zeta", Version: "1.0.0"}},
			{PackageVersion: PackageVersion{Name: "alpha", Version: "1.10.0"}},
			{PackageVersion: PackageVersion{Name: "alpha", Version: "1.9.0"}},
			{PackageVersion: PackageVersion{Name: "alpha", Version: "1.9.0"}},
			{PackageVersion: PackageVersion{Name: "@scope/pkg", Version: "2.0.0"}},
		},
	}

	var buf bytes.Buffer
	if err := renderAffectedPackagesCSV(result, &buf); err != nil {
		t.Fatalf("renderAffectedPackagesCSV: %v", err)
	}

	raw := buf.String()
	rows, err := csv.NewReader(strings.NewReader(raw)).ReadAll()
	if err != nil {
		t.Fatalf("output is not valid CSV: %v", err)
	}

	want := [][]string{
		{"package_name", "vulnerable_versions"},
		{"@scope/pkg", "2.0.0"},
		// Duplicates collapse and 1.9.0 sorts before 1.10.0.
		{"alpha", "1.9.0,1.10.0"},
		{"zeta", "1.0.0"},
	}
	if !reflect.DeepEqual(rows, want) {
		t.Errorf("got  %q\nwant %q", rows, want)
	}

	// The multi-version field must be quoted, or the file is unparseable.
	if !strings.Contains(raw, `"1.9.0,1.10.0"`) {
		t.Errorf("multi-version field is not quoted:\n%s", raw)
	}
}

// A run's affected-packages.csv is a valid --csv input for the next run.
func TestAffectedPackagesCSVRoundTripsThroughTheParser(t *testing.T) {
	result := &BlastResult{
		Affected: []AffectedPackage{
			{PackageVersion: PackageVersion{Name: "axios", Version: "1.14.1"}},
			{PackageVersion: PackageVersion{Name: "axios", Version: "0.30.4"}},
			{PackageVersion: PackageVersion{Name: "@scope/pkg", Version: "2.0.0"}},
		},
	}

	var buf bytes.Buffer
	if err := renderAffectedPackagesCSV(result, &buf); err != nil {
		t.Fatalf("renderAffectedPackagesCSV: %v", err)
	}

	got, err := ParseCompromisedCSV(writeCSV(t, buf.String()), NPM)
	if err != nil {
		t.Fatalf("ParseCompromisedCSV: %v", err)
	}

	want := []TargetSpec{
		{System: NPM, Name: "@scope/pkg", Versions: []string{"2.0.0"}},
		{System: NPM, Name: "axios", Versions: []string{"0.30.4", "1.14.1"}},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got  %+v\nwant %+v", got, want)
	}
}
